[build-system]
requires = ["setuptools>=61", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "Al Niessner", email = "Al.Niessner@xxx.xxx.gov" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Development Status :: 5 -- Production/Stable",
]
description = "ROMAN CGI Data Integration Processor (DIP)"
dynamic = ["version"]
license = { file = "LICENSE.txt" }
name = "DIP"
readme = "README.md"
requires-python = ">=3.11"

[project.urls]
Homepage = "https://roman-corgi.github.io/ctc-dip/"

[tool.setuptools]
packages = { find = {} }

[tool.setuptools.package-data]
"dip.basis" = ["*.dot"]
"dip.base" = ["*.xml"]

[tool.setuptools_scm]
fallback_version = "0.0.0"
version_file = "dip/_version.py"
