name: Update Documentation

on:
  push:
    paths:
      - 'dip/basis/*.dot'  # Only runs when .dot files in this folder change

jobs:
  render_graphs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Create output directory
        run: mkdir -p docs/assets/images

      - name: Process DOT files
        run: |
          for file in dip/basis/*.dot; do
            # Get filename without extension
            filename=$(basename "$file" .dot)
            echo "Processing $filename..."
            
            # Generate PNG and SVG
            # dot -Tpng "$file" -o "docs/assets/images/${filename}.png"
            dot -Tsvg "$file" -o "docs/assets/images/${filename}.svg"

            # Generate docs page
            if ! command -v envsubst &> /dev/null; then
              sudo apt-get update && sudo apt-get install -y gettext-base
            fi
            docdir=""
            case "$filename" in
              cal_*)
                docdir="docs/design/calibration/$filename"
                parent=Calibration
                ;;
              ch_*)
                docdir="docs/design/channel/$filename"
                parent=Channel
                ;;
              ck_*)
                dockdir"docs/design/clerk/$filename"
                parent=Clerk
                ;;
            esac
            if [ -n "$docdir" ]
            then
                mkdir -p "$docdir"
                name="${filename#*_}"
                export filename name parent
                envsubst < docs/design/README.template > "$docdir/README.md"
            fi
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/images/*.png docs/assets/images/*.svg
          
          # Only commit if there are actual changes to images
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated diagrams from dip/basis"
            git push
          fi
