name: Static Analysis
run-name: ${{ github.actor }} is checking code quality/style for merge compliance
on: [pull_request]
jobs:
  Build:
    name: Generating Code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: build
        run: tools/build.sh ignore_checks
  Style:
    name: Coding Style
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: black
        run: black --check --diff -l 80 --skip-string-normalization --exclude="(workflows/local|binding.py)" .
  Linters:
    name: Code Quality
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: pylint
        run: pylint --ignore=bindings --rcfile .github/workflows/pylint.rc -ry -sy dip
      - name: flake8
        run: flake8 --exclude=bindings --ignore E501,E203,W503 dip
  Security:
    name: Code Security
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: bandit
        run: |
          bandit -f json -b .github/workflows/bandit_baseline.json -r dip
          bandit -f json -o .github/workflows/bandit_full.json -r dip || exit 0
  Delivery:
    name: Deployment (pypi) Compliance
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: pyroma
        run: pyroma --min 10 .
  Compliance:
    name: DAWGIE Compliance
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r .github/workflows/requirements.txt
      - name: Compliance
        env:
          CORGIDRP_DO_NOT_AUTO_INIT_CALDB: True
          LDTK_ROOT: ${{ runner.temp }}/.ldtk
        run: |
          python -m dawgie.tools.compliant --ae-dir=dip --ae-pkg=dip
